{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ template "redis-ha.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints }}
  routes:
  - match: {{ template "redis-ha.ingressRouteMatch" . }}
    kind: Rule
    services:
    - name: {{ template "redis-ha.fullname" . }}-haproxy
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.redis.port }}
  tls: {}
{{- end }}
